"""Post-process digest for better formatting"""

from datetime import datetime


def add_metadata(digest, items_count, feeds_count, cost_estimate):
    """Add header with metadata."""

    header = f"""---
Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
Sources: {items_count} items from {feeds_count} feeds
Estimated Cost: ${cost_estimate:.3f}
---

"""
    return header + digest


def add_footer(digest):
    """Add footer with actions."""

    footer = """

---

## 📌 Actions

- [ ] Follow up on interesting stories
- [ ] Share key insights with team
- [ ] Archive or tag for reference

*Generated by AI RSS Summarizer*
"""
    return digest + footer


def format_digest(digest, items_count, feeds_count, cost_estimate):
    """Apply all formatting to digest."""

    formatted = add_metadata(digest, items_count, feeds_count, cost_estimate)
    formatted = add_footer(formatted)

    return formatted
